# Generated by Django 6.0.2 on 2026-03-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("price", models.IntegerField()),
                ("fuel_type", models.CharField(max_length=50)),
                ("transmission", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
    ]
