# Generated by Django 6.0.2 on 2026-03-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
    ]
