# Generated by Django 6.0.2 on 2026-03-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
