# Generated by Django 6.0.2 on 2026-03-01 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_contact_location_contact_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="model",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="location",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="phone",
        ),
        migrations.AddField(
            model_name="car",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(default=0, upload_to="cars/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="car",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
