# Generated by Django 6.0.2 on 2026-03-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_remove_car_model_remove_contact_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
