# Generated by Django 6.0.2 on 2026-03-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_car_location_car_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="status",
            field=models.CharField(
                choices=[("available", "Available"), ("sold", "Sold")],
                default="available",
                max_length=20,
            ),
        ),
    ]
