# Generated by Django 6.0.2 on 2026-03-02 19:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_car_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
